In [1]:
#imprt the library
import pandas as pd

In [2]:
#create dataframe
data={ "Date": [
        "2024-01-05", "2024-01-10", "2024-02-12",
        "2024-02-18", "2024-03-03", "2024-03-15"
    ],
    "Product": ["Laptop", "Mobile", "Laptop", "Tablet", "Mobile", "Laptop"],
    "Price": [50000, 20000, 52000, 15000, 21000, 51000],
    "Quantity": [2, 3, 1, 4, 2, 1]
     }
df=pd.DataFrame(data)

In [3]:
#show dataframe
df

         Date Product  Price  Quantity
0  2024-01-05  Laptop  50000         2
1  2024-01-10  Mobile  20000         3
2  2024-02-12  Laptop  52000         1
3  2024-02-18  Tablet  15000         4
4  2024-03-03  Mobile  21000         2
5  2024-03-15  Laptop  51000         1

In [4]:
# showing detailed info about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      6 non-null      object
 1   Product   6 non-null      object
 2   Price     6 non-null      int64
 3   Quantity  6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [5]:
# need to convert Date column from 'object' type to 'DateTime'
df['Date']=pd.to_datetime(df['Date'])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      6 non-null      datetime64[ns]
 1   Product   6 non-null      object
 2   Price     6 non-null      int64
 3   Quantity  6 non-null      int64
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 324.0+ bytes

## calculating most selled product

In [11]:
product_sales=df.groupby('Product')['Quantity'].sum()
product_sales

Product
Laptop    4
Mobile    5
Tablet    4
Name: Quantity, dtype: int64

In [10]:
# most selled product
product_sales.idxmax()

'Mobile'

## Total revenue
revenue is quantity*price

In [13]:
#calculating revenue and adding it as a new column
df['Revenue']=df['Price']*df['Quantity']
df

        Date Product  Price  Quantity  Revenue
0 2024-01-05  Laptop  50000         2   100000
1 2024-01-10  Mobile  20000         3    60000
2 2024-02-12  Laptop  52000         1    52000
3 2024-02-18  Tablet  15000         4    60000
4 2024-03-03  Mobile  21000         2    42000
5 2024-03-15  Laptop  51000         1    51000

In [14]:
# grouping the products and calculating product-wise revenue
df.groupby('Product')['Revenue'].sum()

Product
Laptop    203000
Mobile    102000
Tablet     60000
Name: Revenue, dtype: int64

In [15]:
#total revenue
df['Revenue'].sum()

np.int64(365000)