In [1]:
#imprt the library
import pandas as pd

In [2]:
#create dataframe
data={ "Date": [
        "2024-01-05", "2024-01-10", "2024-02-12",
        "2024-02-18", "2024-03-03", "2024-03-15"
    ],
    "Product": ["Laptop", "Mobile", "Laptop", "Tablet", "Mobile", "Laptop"],
    "Price": [50000, 20000, 52000, 15000, 21000, 51000],
    "Quantity": [2, 3, 1, 4, 2, 1]
     }
df=pd.DataFrame(data)

In [3]:
#show dataframe
df

         Date Product  Price  Quantity
0  2024-01-05  Laptop  50000         2
1  2024-01-10  Mobile  20000         3
2  2024-02-12  Laptop  52000         1
3  2024-02-18  Tablet  15000         4
4  2024-03-03  Mobile  21000         2
5  2024-03-15  Laptop  51000         1

In [4]:
# showing detailed info about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      6 non-null      object
 1   Product   6 non-null      object
 2   Price     6 non-null      int64
 3   Quantity  6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [5]:
# need to convert Date column from 'object' type to 'DateTime'
df['Date']=pd.to_datetime(df['Date'])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      6 non-null      datetime64[ns]
 1   Product   6 non-null      object
 2   Price     6 non-null      int64
 3   Quantity  6 non-null      int64
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 324.0+ bytes

## calculating most selled product

In [7]:
product_sales=df.groupby('Product')['Quantity'].sum()
product_sales

Product
Laptop    4
Mobile    5
Tablet    4
Name: Quantity, dtype: int64

In [8]:
# most selled product
product_sales.idxmax()

'Mobile'

## Total revenue
revenue is quantity*price

In [9]:
#calculating revenue and adding it as a new column
df['Revenue']=df['Price']*df['Quantity']
df

        Date Product  Price  Quantity  Revenue
0 2024-01-05  Laptop  50000         2   100000
1 2024-01-10  Mobile  20000         3    60000
2 2024-02-12  Laptop  52000         1    52000
3 2024-02-18  Tablet  15000         4    60000
4 2024-03-03  Mobile  21000         2    42000
5 2024-03-15  Laptop  51000         1    51000

In [10]:
# grouping the products and calculating product-wise revenue
df.groupby('Product')['Revenue'].sum()

Product
Laptop    203000
Mobile    102000
Tablet     60000
Name: Revenue, dtype: int64

In [11]:
#total revenue
df['Revenue'].sum()

np.int64(365000)

## Monthly sales analysis

In [12]:
#extract month
df['Month']=df['Date'].dt.month
df

        Date Product  Price  Quantity  Revenue  Month
0 2024-01-05  Laptop  50000         2   100000      1
1 2024-01-10  Mobile  20000         3    60000      1
2 2024-02-12  Laptop  52000         1    52000      2
3 2024-02-18  Tablet  15000         4    60000      2
4 2024-03-03  Mobile  21000         2    42000      3
5 2024-03-15  Laptop  51000         1    51000      3

In [13]:
# grouping the data month-wise
#summing up monthwise revenue
# and then sorting the monthly revenue in descending order

monthly_revenue=df.groupby('Month')['Revenue'].sum().sort_values(ascending=False)
monthly_revenue

Month
1    160000
2    112000
3     93000
Name: Revenue, dtype: int64

In [14]:
## Highest revenue month
monthly_revenue.idxmax()

np.int32(1)

In [15]:
## highest revenue day
df.loc[df['Revenue'].idxmax()]

Date        2024-01-05 00:00:00
Product                  Laptop
Price                     50000
Quantity                      2
Revenue                  100000
Month                         1
Name: 0, dtype: object

# More Complex Dataset and Problems

In [16]:
data = {
    "Date": [
        "2024-01-05","2024-01-10","2024-01-15",
        "2024-02-12","2024-02-18","2024-02-25",
        "2024-03-03","2024-03-10","2024-03-15",
        "2024-04-02","2024-04-08","2024-04-20",
        "2024-05-05","2024-05-12","2024-05-25"
    ],
    "Product": [
        "Laptop","Mobile","Tablet",
        "Laptop","Tablet","Mobile",
        "Mobile","Laptop","Tablet",
        "Laptop","Mobile","Tablet",
        "Mobile","Laptop","Tablet"
    ],
    "Price": [
        50000,20000,15000,
        52000,15000,21000,
        22000,51000,14000,
        53000,23000,16000,
        24000,55000,17000
    ],
    "Quantity": [
        2,3,4,
        1,2,2,
        3,1,5,
        2,2,3,
        1,2,4
    ],
    "City": [
        "Delhi","Mumbai","Delhi",
        "Bangalore","Delhi","Mumbai",
        "Delhi","Bangalore","Mumbai",
        "Delhi","Mumbai","Bangalore",
        "Delhi","Mumbai","Bangalore"
    ]
}

df = pd.DataFrame(data)

df["Date"] = pd.to_datetime(df["Date"])
df["Revenue"] = df["Price"] * df["Quantity"]

df

         Date Product  Price  Quantity       City  Revenue
0  2024-01-05  Laptop  50000         2      Delhi   100000
1  2024-01-10  Mobile  20000         3     Mumbai    60000
2  2024-01-15  Tablet  15000         4      Delhi    60000
3  2024-02-12  Laptop  52000         1  Bangalore    52000
4  2024-02-18  Tablet  15000         2      Delhi    30000
5  2024-02-25  Mobile  21000         2     Mumbai    42000
6  2024-03-03  Mobile  22000         3      Delhi    66000
7  2024-03-10  Laptop  51000         1  Bangalore    51000
8  2024-03-15  Tablet  14000         5     Mumbai    70000
9  2024-04-02  Laptop  53000         2      Delhi   106000
10 2024-04-08  Mobile  23000         2     Mumbai    46000
11 2024-04-20  Tablet  16000         3  Bangalore    48000
12 2024-05-05  Mobile  24000         1      Delhi    24000
13 2024-05-12  Laptop  55000         2     Mumbai   110000
14 2024-05-25  Tablet  17000         4  Bangalore    68000

## Revenue per city

group the dataframe by cities ( all same citiies groups would be created) using groupby() method ,
then sum the on the revenue column using sum()

In [17]:
city_revenue=df.groupby('City')['Revenue'].sum()

In [18]:
city_revenue

City
Bangalore    219000
Delhi        386000
Mumbai       328000
Name: Revenue, dtype: int64

## Best Performing City
City with the Highest Revenue -- sort in descending order of (revenue_per_city)

In [19]:
best_city=city_revenue.sort_values(ascending=False).idxmax()

best_city

'Delhi'

## least Selling Product

In [20]:
#grouping the products and adding quantity
product_quantity=df.groupby('Product')['Quantity'].sum()

product_quantity

Product
Laptop     8
Mobile    11
Tablet    18
Name: Quantity, dtype: int64

In [21]:
#finding least selling product
product_quantity.idxmin()

'Laptop'

## Which Product Sells Best In Each City

here we are talking about which product is most popular -- the answer of this question we would get by analysing the quantity.

In [22]:
#Group by City and Product --- Adding Qauntity 

product_city_quantity=df.groupby(['City','Product'])['Quantity'].sum()

product_city_quantity

City       Product
Bangalore  Laptop     2
           Tablet     7
Delhi      Laptop     4
           Mobile     4
           Tablet     6
Mumbai     Laptop     2
           Mobile     7
           Tablet     5
Name: Quantity, dtype: int64

In [24]:
# reset index -- gives dataframe
product_city_quantity=product_city_quantity.reset_index()

product_city_quantity

        City Product  Quantity
0  Bangalore  Laptop         2
1  Bangalore  Tablet         7
2      Delhi  Laptop         4
3      Delhi  Mobile         4
4      Delhi  Tablet         6
5     Mumbai  Laptop         2
6     Mumbai  Mobile         7
7     Mumbai  Tablet         5

In [25]:
# finding each city most selled product quantity 'index no'

# group by city and find the index no where quantity is max -- using idxmax() function

product_city_quantity.groupby('City')['Quantity'].idxmax()

City
Bangalore    1
Delhi        4
Mumbai       6
Name: Quantity, dtype: int64

In [27]:
# Get the combination where the most selled occured per city

best_per_city=product_city_quantity.loc[product_city_quantity.groupby('City')['Quantity'].idxmax()]

best_per_city

        City Product  Quantity
1  Bangalore  Tablet         7
4      Delhi  Tablet         6
6     Mumbai  Mobile         7